version: "3.7"

services:
  nginx1:
    image: nginx:latest
    ports:
      - 8000:80

  nginx2:
    image: nginx:latest
    ports:
      - 8060:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html